language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_install: cd app/api
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coverage
  - npm run coveralls
  - npm run report-coverage
