language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    repo_token:
      secure: "abRgvzRNu1vJW7q7rh7vKUbP0hxyFZyNdrP8yIO+jlxBYOHUuJCsOpumRQm2br++wj0dAAxpEHbuGGDgnyeQ3cHDuvUtWY402hjioxaM7AV9YTZjzJZ5wimYltWk9Ghfwbcp6cY9XRBDTaxWb+Ny2CfwC4iPzQP7lpz4h9OAuzrN7t/PFd5uKNm/j0inPhqa9bT4/7D5+iwQ5HhDxjTPGGk1QrQt/ixC9NLR9dPKTCaQQC73MIcDNZUL2tdydeDlj523RuI+UGFjSKtMIo1u+EWDZLnruc+FWxig1V/Jfns460omJUL4xIh2JjlwIGkY8Pty+/YLZfm1zqLZ0Rev6z70h87AU6lydm26x2FhNmb+3eM1WJqiR9d05GDSnqtEDqvyH74LFwSEaSu24y2oCJnOdjGkE1IGU5CUiEUrg4uCvn+tZwXq6hUSDwUv4/TQOPUJ40RIZqKtdkWuQp7str/wIPg4e7sfBYQJcRSgdpS4eOwgA4JecLjgvBCzms7Pouxlf0MwwTqqzfdNOAWu+VrPpawo8LigtghoRvZQuxxkooLGQa8QVGuIFKR59wpDB19aiqHOGoUtXcjQEYe1FbP3t927Sy3JOhlR2o+xhBfcD9KrKcge9WndGX5aNVsJY7dRVQMPkWj8ToLhaz6EDnAzjTjiMtqq5KU7TOtboL8="
before_install: cd app/api
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coverage
after_script:
  - npm install codeclimate-test-reporter && cat coverage/lcov.info | codeclimate-test-reporter
